//Enum for types of available tiles
export enum tileType {
  SIDEWAY = "SIDEWAY",
  STREET_CURVE = "STREET_CURVE",
  STREET_STRAIGHT = "STREET_STRAIGHT",
  STREET_CROSS = "STREET_CROSS",
  STREET_T_CROSS = "STREET_T_CROSS",
  RAIL_STRAIGHT = "RAIL_STRAIGHT",
  RAIL_CURVE = "RAIL_CURVE",
  GRASSTILE = "GRASSTILE",
  PEDESTRIAN_CROSSING = "PEDESTRIAN_CROSSING",
  FARM = "FARM",
}
