export enum TileName {
  STREET_STRAIGHT = "STREET_STRAIGHT",
  STREET_CURVE = "STREET_CURVE",
  STREET_T_CROSS = "STREET_T_CROSS",
  STREET_CROSS = "STREET_CROSS",
  PEDESTRIAN_CROSSING = "PEDESTRIAN_CROSSING",
  SIDEWAY = "SIDEWAY",
  SIDEWAY_BICYCLE_CURVE = "SIDEWAY_BICYCLE_CURVE",
  SIDEWAY_PASSENGER_CURVE = "SIDEWAY_PASSENGER_CURVE",
  FARM = "FARM",
}
