export enum TileName {
  STREET_STRAIGHT = "STREET_STRAIGHT",
  STREET_CURVE = "STREET_CURVE",
  STREET_T_CROSS = "STREET_T_CROSS",
  STREET_CROSS = "STREET_CROSS",
  SIDEWAY = "SIDEWAY",
  PEDESTRIAN_CROSSING = "PEDESTRIAN_CROSSING",
  FARM = "FARM",
}
